### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by david-rundel** [automl/HW-GPT-Bench#25]
Dear HW-GPT-Bench Team,

Thank you for your impressive and interesting work. Unfortunately, I encountered issues while trying to install the repository as instructed. I attempted the installation in various environments, but it was unsuccessful.

To help illustrate the issue, I have prepared a minimal example demonstrating how the installation fails. You can find it via [this link](https://colab.research.google.com/drive/1DBuM8aC-IRu-7wZtIot0jJezZUN4zx1l?usp=sharing).

I would greatly appreciate your assistance in resolving this matter.

Kind regards,
David

**Comment by rheasukthanker** [comment]
Thanks for reporting this! Could you try reproducing the issue for python version `3.11.9` as suggested in the readme? Also just FYI, we are currently refactoring the code and this should be done over the next couple of days.

**Comment by david-rundel** [comment]
Thanks a lot!
